# Generated by Django 4.2.28 on 2026-02-24 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartments', '0002_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment', 'Payment'), ('lease', 'Lease'), ('maintenance', 'Maintenance'), ('expense', 'Expense'), ('tenant', 'Tenant'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'System Administrator'), ('owner', 'Property Owner'), ('manager', 'Property Manager'), ('accountant', 'Accountant / Finance Officer'), ('maintenance', 'Maintenance Staff'), ('security', 'Security / Gate Officer'), ('tenant', 'Tenant')], default='tenant', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, help_text='National ID/Passport', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('kra_pin', models.CharField(blank=True, help_text='KRA PIN (Kenya)', max_length=20)),
                ('years_experience', models.IntegerField(blank=True, default=0)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('skill_type', models.CharField(blank=True, help_text='For maintenance: Plumber, Electrician, etc.', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=50)),
                ('mpesa_till', models.CharField(blank=True, max_length=50)),
                ('can_add_tenants', models.BooleanField(default=False)),
                ('can_approve_payments', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('off', 'Off Duty')], default='available', max_length=20)),
                ('shift', models.CharField(blank=True, choices=[('day', 'Day'), ('night', 'Night')], max_length=20)),
                ('supervisor_name', models.CharField(blank=True, max_length=200)),
                ('assigned_gate', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_electricity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_water',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/receipts/'),
        ),
        migrations.AddField(
            model_name='lease',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='notice_period_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/after/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to_name',
            field=models.CharField(blank=True, help_text='Contractor or staff assigned', max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/before/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('appliances', 'Appliances'), ('hvac', 'HVAC'), ('pest_control', 'Pest Control'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment Building'), ('bedsitter', 'Bedsitter'), ('commercial', 'Commercial Building'), ('land', 'Land'), ('villa', 'Villa'), ('house', 'House')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='title_deed_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='water_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='employer_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_copy',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/ids/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='lease_agreement',
            field=models.FileField(blank=True, null=True, upload_to='tenants/leases/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='next_of_kin_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('one_bed', '1 Bedroom'), ('two_bed', '2 Bedroom'), ('three_bed', '3 Bedroom'), ('four_bed', '4 Bedroom'), ('penthouse', 'Penthouse'), ('bedsitter', 'Bedsitter')], db_index=True, default='one_bed', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('repairs', 'Repairs'), ('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('management', 'Management Fee'), ('security', 'Security'), ('cleaning', 'Cleaning'), ('landscaping', 'Landscaping'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(db_index=True, help_text='Lease end date'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(db_index=True, help_text='Lease start date'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('cheque', 'Cheque'), ('card', 'Card')], db_index=True, default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('income', 'Income Report'), ('occupancy', 'Occupancy Report'), ('maintenance', 'Maintenance Report'), ('financial', 'Financial Report'), ('tenant', 'Tenant Report'), ('expense', 'Expense Report')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], db_index=True, default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id_number',
            field=models.CharField(db_index=True, help_text='National ID/Passport number', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['property', 'status'], name='apartments__propert_84fc26_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['apartment_type'], name='apartments__apartme_133e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-expense_date'], name='apartments__expense_5bda09_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'expense_date'], name='apartments__categor_00f82a_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='apartments__status_af582b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['-created_at'], name='apartments__created_ee7e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status', 'priority'], name='apartments__status_6f14a7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='apartments__payment_cb7aea_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_date'], name='apartments__status_653b92_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='apartments__created_eb4aee_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['-created_at'], name='apartments__created_e12e61_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['last_name', 'first_name'], name='apartments__last_na_7ce925_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='apartments.property'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='apartments__recipie_f85d1b_idx'),
        ),
    ]
