# Generated by Django 4.2.28 on 2026-02-25 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartments', '0003_notification_userprofile_apartment_has_electricity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description'),
        ),
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL (e.g., from GitHub)', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_username',
            field=models.CharField(blank=True, help_text='Username if target is specific user', max_length=150),
        ),
        migrations.AddField(
            model_name='notification',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="Social media links as JSON: {'facebook': 'url', 'twitter': 'url', 'instagram': 'url', 'linkedin': 'url', 'youtube': 'url', 'tiktok': 'url', 'whatsapp': 'url'}"),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('tenants', 'Tenants Only'), ('owners', 'Property Owners'), ('staff', 'Staff Members'), ('specific', 'Specific User')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Main link (e.g., Google form)', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('lease', 'Lease'), ('maintenance', 'Maintenance'), ('expense', 'Expense'), ('tenant', 'Tenant'), ('system', 'System'), ('announcement', 'Announcement'), ('social', 'Social Media')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
