# Generated by Django 4.2.28 on 2026-02-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_notification_description_notification_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_lease',
            field=models.BooleanField(default=False, help_text='Can create lease agreements'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_maintenance',
            field=models.BooleanField(default=False, help_text='Can create maintenance requests'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_payment',
            field=models.BooleanField(default=False, help_text='Can record payments'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_apartments',
            field=models.BooleanField(default=False, help_text='Can add/edit apartments'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_properties',
            field=models.BooleanField(default=False, help_text='Can add/edit properties'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Can manage user accounts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_all_maintenance',
            field=models.BooleanField(default=False, help_text='Can view all maintenance requests'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_all_payments',
            field=models.BooleanField(default=False, help_text='Can view all payment records'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_add_tenants',
            field=models.BooleanField(default=False, help_text='Can add new tenants'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_approve_payments',
            field=models.BooleanField(default=False, help_text='Can approve payments'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Can view financial reports'),
        ),
    ]
